version: '3'

services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: webapp_db
      POSTGRES_USER: webapp_user
      POSTGRES_PASSWORD: postgres1234

  webapp:
    image: ghcr.io/mubeena12/docker-webapp:latest
    network_mode: "host"
    restart: always
    devices: 
     - /dev/mpl3115a2
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: postgresql://webapp_user:postgres1234@postgres-db/webapp_db
